image: 192.168.1.4:5000/node-alpine:v1.0.0

stages:
  - install_deps
  - build
  - deploy_dist

cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/

install_deps:
  stage: install_deps
  tags:
    - ant-pro-runner
  script:
    - npm config set registry http://192.168.1.4:8081/repository/npm-group/
    #- npm config set registry http://registry.npm.taobao.org
    - npm cache verify
    #- npm config get cache
    - npm install

build_job:
  stage: build
  tags:
    - ant-pro-runner
  script:
    - ls .
    #- ls /usr/local/lib/node_modules/
    - npm run build
    - ls .
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy_dist
  tags:
    - ant-pro-runner
  script:
    - ls .