image: node:10.17.0-alpine

stages:
  - package
  - deploy_dist
cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
build_job:
  stage: package
  tags:
    - ant-pro-runner
  script:
    - npm config set registry http://192.168.1.4:8081/repository/npm-group/
    - npm install
    - npm run build
deploy_job:
  stage: deploy_dist
  tags:
    - ant-pro-runner
  script:
    - ls .