image: node:10.17.0-alpine

stages:
  - install_deps
  - build
  - deploy_dist
cache:
    paths:
      - root/.npm/
      - node_modules/
install_deps:
  stage: install_deps
  tags:
    - ant-pro-runner
  script:
    - npm config set registry http://192.168.1.4:8081/repository/npm-group/
    #- npm config set registry http://registry.npm.taobao.org
    - npm cache verify
    - npm install -g umi
    - umi -v
    - npm install

build_job:
  stage: build
  tags:
    - ant-pro-runner
  script:
    - npm run build  

deploy_job:
  stage: deploy_dist
  tags:
    - ant-pro-runner
  script:
    - ls .