image: node:10.17.0-alpine

stages:
  - install_deps
  - build
  - deploy_dist
cache:
    paths:
      - /usr/local/lib/node_modules/
      - node_modules/
install_deps:
  stage: install_deps
  tags:
    - ant-pro-runner
  script:
    - npm config set registry http://192.168.1.4:8081/repository/npm-group/
    #- npm config set registry http://registry.npm.taobao.org
    - npm cache verify
    - npm config get cache
    - npm install -g umi
    - npm install
    - ls /usr/local/lib/node_modules/
    - umi -v

build_job:
  stage: build
  tags:
    - ant-pro-runner
  script:
    - ls /usr/local/lib/node_modules/
    - npm -v
    - npm run build  

deploy_job:
  stage: deploy_dist
  tags:
    - ant-pro-runner
  script:
    - ls .