image: 192.168.1.4:5000/node-alpine:v1.0.0

stages:
  - install_deps
  - build
  - deploy_dist

install_deps:
  stage: install_deps
  tags:
    - ant-pro-runner
  script:
    # 先ln 会报创建node_modules 已存在错误所以，只能install 后cp 过去
    - ls .
    - npm config set registry http://192.168.1.4:8081/repository/npm-group/
    #- npm config set registry http://registry.npm.taobao.org
    - npm cache verify
    #- npm config get cache
    - npm install
    - mkdir -r /root/modules/base-ant-pro/node_modules
    - cp -R node_modules /root/modules/base-ant-pro/node_modules
    
build_job:
  stage: build
  tags:
    - ant-pro-runner
  script:
    - ln -s /root/modules/base-ant-pro/node_modules node_modules
    - ls .
    - ls node_modules
    #- ls /usr/local/lib/node_modules/
    - npm run build
    - ls .
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy_dist
  tags:
    - ant-pro-runner
  script:
    - ls .